TARGET = tarea8
$(TARGET): main.c arboles_binarios/arboles_binarios.c arboles_binarios/funciones.c hash/hash.c
	gcc -o $(TARGET) main.c arboles_binarios/arboles_binarios.c arboles_binarios/funciones.c hash/hash.c

run:
	./tarea8

clean:
	rm -f $(TARGET)